# Generated by Django 4.2.28 on 2026-02-16 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WindowEstimationLog",
            fields=[
                ("wid", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=100)),
                ("test_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("window_event", models.IntegerField()),
                ("transaction_log", models.DateTimeField(auto_now_add=True)),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "window_estimation_log",
                "ordering": ["-transaction_log"],
                "indexes": [
                    models.Index(
                        fields=["email", "test_id"], name="window_esti_email_2376aa_idx"
                    ),
                    models.Index(fields=["uid"], name="window_esti_uid_b35701_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProctoringLog",
            fields=[
                ("pid", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("test_id", models.CharField(max_length=100)),
                ("voice_db", models.IntegerField(default=0)),
                ("img_log", models.TextField()),
                ("user_movements_updown", models.IntegerField()),
                ("user_movements_lr", models.IntegerField()),
                ("user_movements_eyes", models.IntegerField()),
                ("phone_detection", models.IntegerField()),
                ("person_status", models.IntegerField()),
                ("log_time", models.DateTimeField(auto_now_add=True)),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "proctoring_log",
                "ordering": ["-log_time"],
                "indexes": [
                    models.Index(fields=["email"], name="proctoring__email_f5e71f_idx"),
                    models.Index(
                        fields=["email", "test_id"], name="proctoring__email_8bae57_idx"
                    ),
                    models.Index(fields=["uid"], name="proctoring__uid_dc4955_idx"),
                ],
            },
        ),
    ]
