"""
URL configuration for quizapp project.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from exams.views import (
    give_test_view,
    give_test_exam_view,
    generate_test_view,
    viewquestions_view,
    display_questions_view,
    update_disp_questions_view,
    delete_disp_questions_view,
    updatetidlist_view,
    deltidlist_view,
    disptests_view,
    livemonitoringtid_view,
    viewstudentslogs_view,
    insertmarkstid_view,
    publish_results_testid_view,
    tests_created_view,
    randomize_view,
    window_event_view,
    video_feed_view,
    calculator_view,
    create_test_view,
    create_test_lqa_view,
    create_test_pqa_view,
    payment_view,
    create_checkout_session_view,
    success_view,
    cancel_view,
    update_objective_question_view,
    update_long_question_view,
    update_practical_question_view,
    delete_questions_view,
    live_monitoring_view,
    display_students_details_view,
    student_monitoring_stats_view,
    ajax_student_monitoring_stats_view,
    winevent_students_logs_view,
    person_display_students_logs_view,
    mob_display_students_logs_view,
    audio_display_students_logs_view,
    display_students_logs_view,
    insert_marks_details_view,
    insert_obj_marks_view,
    insert_sub_marks_view,
    insert_prac_marks_view,
    view_results_view,
    publish_results_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('give-test/', give_test_view, name='give_test'),
    path('give-test/<str:test_id>/', give_test_exam_view, name='give_test_exam'),
    path('test-login/', lambda request: render(request, 'test_login.html'), name='test_login'),
    # Professor exam management
    path('generate_test/', generate_test_view, name='generate_test'),
    path('generate_test/test_generate', generate_test_view, name='generate_test_legacy'),  # Without trailing slash to match form POST
    path('viewquestions/', viewquestions_view, name='viewquestions'),
    path('viewquestions/displayquestions', display_questions_view, name='display_questions'),
    path('updatetidlist/', updatetidlist_view, name='updatetidlist'),
    path('updatetidlist/updatedispques', update_disp_questions_view, name='update_disp_questions'),
    path('deltidlist/', deltidlist_view, name='deltidlist'),
    path('deltidlist/deldispques', delete_disp_questions_view, name='delete_disp_questions'),
    path('disptests/', disptests_view, name='disptests'),
    path('livemonitoringtid/', livemonitoringtid_view, name='livemonitoringtid'),
    path('live_monitoring', live_monitoring_view, name='live_monitoring'),
    path('viewstudentslogs/', viewstudentslogs_view, name='viewstudentslogs'),
    path('viewstudentslogs/displaystudentsdetails', display_students_details_view, name='display_students_details'),
    path('viewstudentslogs/studentmonitoringstats/<str:test_id>/<str:email>/', student_monitoring_stats_view, name='student_monitoring_stats'),
    path('ajaxstudentmonitoringstats/<str:test_id>/<str:email>/', ajax_student_monitoring_stats_view, name='ajax_student_monitoring_stats'),
    path('wineventstudentslogs/<str:test_id>/<str:email>/', winevent_students_logs_view, name='winevent_students_logs'),
    path('persondisplaystudentslogs/<str:test_id>/<str:email>/', person_display_students_logs_view, name='person_display_students_logs'),
    path('mobdisplaystudentslogs/<str:test_id>/<str:email>/', mob_display_students_logs_view, name='mob_display_students_logs'),
    path('audiodisplaystudentslogs/<str:test_id>/<str:email>/', audio_display_students_logs_view, name='audio_display_students_logs'),
    path('displaystudentslogs/<str:test_id>/<str:email>/', display_students_logs_view, name='display_students_logs'),
    path('insertmarkstid/', insertmarkstid_view, name='insertmarkstid'),
    path('insertmarkstid/insertmarksdetails', insert_marks_details_view, name='insert_marks_details'),
    path('insertobjmarks/<str:test_id>/<str:email>/', insert_obj_marks_view, name='insert_obj_marks'),
    path('insertsubmarks/<str:test_id>/<str:email>/', insert_sub_marks_view, name='insert_sub_marks'),
    path('insertpracmarks/<str:test_id>/<str:email>/', insert_prac_marks_view, name='insert_prac_marks'),
    path('viewresults', view_results_view, name='view_results'),
    path('publish_results', publish_results_view, name='publish_results'),
    path('publish-results-testid/', publish_results_testid_view, name='publish_results_testid'),
    path('tests-created/', tests_created_view, name='tests_created'),
    path('randomize', randomize_view, name='randomize'),
    path('window_event', window_event_view, name='window_event'),
    path('video_feed', video_feed_view, name='video_feed'),
    path('calc', calculator_view, name='calculator'),
    path('create-test', create_test_view, name='create_test'),
    path('create_test_lqa', create_test_lqa_view, name='create_test_lqa'),
    path('create_test_pqa', create_test_pqa_view, name='create_test_pqa'),
    path('payment/', payment_view, name='payment'),
    path('create-checkout-session/', create_checkout_session_view, name='create_checkout_session'),
    path('success/', success_view, name='success'),
    path('cancel/', cancel_view, name='cancel'),
    # Update question URLs (these are also duplicated in exams.urls for backward compatibility)
    path('update/<str:test_id>/<str:qid>/', update_objective_question_view, name='update_objective_question'),
    path('updateLQA/<str:test_id>/<str:qid>/', update_long_question_view, name='update_long_question'),
    path('updatePQA/<str:test_id>/<str:qid>/', update_practical_question_view, name='update_practical_question'),
    path('delete_questions/<str:test_id>/', delete_questions_view, name='delete_questions'),
    path('exams/', include('exams.urls')),
    path('proctoring/', include('proctoring.urls')),
]

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
