# Generated by Django 4.2.28 on 2026-02-16 17:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("tid", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=100)),
                ("test_id", models.CharField(max_length=100)),
                ("test_type", models.CharField(max_length=75)),
                ("start", models.DateTimeField(auto_now=True)),
                ("end", models.DateTimeField()),
                (
                    "duration",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("show_ans", models.IntegerField(default=0)),
                ("password", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=100)),
                ("neg_marks", models.IntegerField(default=0)),
                ("calc", models.IntegerField(default=0)),
                ("proctoring_type", models.IntegerField(default=0)),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teachers",
                "indexes": [
                    models.Index(
                        fields=["email", "uid"], name="teachers_email_0d83fb_idx"
                    ),
                    models.Index(
                        fields=["test_id"], name="teachers_test_id_c5ab1d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentTestInfo",
            fields=[
                ("stiid", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=100)),
                ("test_id", models.CharField(max_length=100)),
                ("time_left", models.IntegerField()),
                ("completed", models.IntegerField(default=0)),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "studenttestinfo",
                "indexes": [
                    models.Index(
                        fields=["email", "test_id"], name="studenttest_email_3729e7_idx"
                    ),
                    models.Index(fields=["uid"], name="studenttest_uid_f853e6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("sid", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=100)),
                ("test_id", models.CharField(max_length=100)),
                ("qid", models.CharField(blank=True, max_length=25, null=True)),
                ("ans", models.TextField(blank=True, null=True)),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "indexes": [
                    models.Index(
                        fields=["email", "test_id"], name="students_email_3acb8d_idx"
                    ),
                    models.Index(fields=["uid"], name="students_uid_8bf1f1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "questions_uid",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("test_id", models.CharField(max_length=100)),
                ("qid", models.CharField(max_length=25)),
                ("q", models.TextField()),
                ("a", models.CharField(max_length=100)),
                ("b", models.CharField(max_length=100)),
                ("c", models.CharField(max_length=100)),
                ("d", models.CharField(max_length=100)),
                ("ans", models.CharField(max_length=10)),
                (
                    "marks",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "indexes": [
                    models.Index(
                        fields=["test_id", "qid"], name="questions_test_id_758adc_idx"
                    ),
                    models.Index(fields=["uid"], name="questions_uid_ccefd9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PracticalTest",
            fields=[
                ("pid", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=100)),
                ("test_id", models.CharField(max_length=100)),
                ("qid", models.CharField(max_length=25)),
                ("code", models.TextField(blank=True, null=True)),
                ("input", models.TextField(blank=True, null=True)),
                ("executed", models.CharField(blank=True, max_length=125, null=True)),
                ("marks", models.IntegerField()),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "practicaltest",
                "indexes": [
                    models.Index(
                        fields=["email", "test_id"], name="practicalte_email_5bcb8c_idx"
                    ),
                    models.Index(fields=["uid"], name="practicalte_uid_54f227_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PracticalQA",
            fields=[
                ("pracqa_qid", models.BigAutoField(primary_key=True, serialize=False)),
                ("test_id", models.CharField(max_length=100)),
                ("qid", models.CharField(max_length=25)),
                ("q", models.TextField()),
                ("compiler", models.IntegerField()),
                ("marks", models.IntegerField()),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "practicalqa",
                "indexes": [
                    models.Index(
                        fields=["test_id", "qid"], name="practicalqa_test_id_a60135_idx"
                    ),
                    models.Index(fields=["uid"], name="practicalqa_uid_c7029e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LongTest",
            fields=[
                (
                    "longtest_qid",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=100)),
                ("test_id", models.CharField(max_length=100)),
                ("qid", models.IntegerField()),
                ("ans", models.TextField()),
                ("marks", models.IntegerField()),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "longtest",
                "indexes": [
                    models.Index(
                        fields=["email", "test_id"], name="longtest_email_fac6f9_idx"
                    ),
                    models.Index(fields=["uid"], name="longtest_uid_54a73e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LongQA",
            fields=[
                ("longqa_qid", models.BigAutoField(primary_key=True, serialize=False)),
                ("test_id", models.CharField(max_length=100)),
                ("qid", models.CharField(max_length=25)),
                ("q", models.TextField()),
                ("marks", models.IntegerField(blank=True, null=True)),
                (
                    "uid",
                    models.ForeignKey(
                        blank=True,
                        db_column="uid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "longqa",
                "indexes": [
                    models.Index(
                        fields=["test_id", "qid"], name="longqa_test_id_7ade12_idx"
                    ),
                    models.Index(fields=["uid"], name="longqa_uid_580e63_idx"),
                ],
            },
        ),
    ]
