# Generated by Django 4.2.28 on 2026-02-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_violationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationlog",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
